### ISSUE TITLE
How to create the csv files?

### ISSUE THREAD

**Issue by arxrean** [yaoyao-liu/mini-imagenet-tools#10]
Thanks for your sharing. Just want to ask how you determine which images will be included in the csv files.

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

These splits are shared among many few-shot works, e.g. [MAML](https://github.com/cbfinn/maml) and [ProtoNets](https://github.com/abdulfatir/prototypical-networks-tensorflow).

We copied these files from <https://github.com/abdulfatir/prototypical-networks-tensorflow/tree/master/data/mini-imagenet/splits>.

If you have any other questions, feel free to add more comments or open another issue.

**Comment by arxrean** [comment]
Thanks for your reply! I have downloaded the imgnet dataset tar file, not from the official site, but from [kaggle](https://www.kaggle.com/c/imagenet-object-localization-challenge/overview). But it looks like all images in it are different from the ones in the csv file. Most ids in the csv file cannot be found in the original dataset. I have requested the data in the official site for about two weeks but have not received any response. 

Actually I just want the original images in the csv files without resizing, and also their bounding box annotations. Do you have any solution? Thanks!

**Comment by yaoyao-liu** [comment]
I know the official website of ImageNet is not working now. I have an alternative solution: you may download ImageNet via [this link](http://academictorrents.com/details/a306397ccf9c2ead27155983c254227c0fd938e2). However, I've never tried it before. So I can't ensure there are no issues for that link.

You can also send the authors an email to ask for the download link.

**Comment by arxrean** [comment]
Yeah I have tried it, but all images in it do not overlap with mini-imgnet images. Anyway thank you!
