### ISSUE TITLE
Hello, do you know how to generate the  pickle file for miniImagenet?

### ISSUE THREAD

**Issue by 123675** [yaoyao-liu/mini-imagenet-tools#13]
Hello, do you know how to generate the  pickle file for miniImagenet?

**Comment by yaoyao-liu** [comment]
I don't use pickle in my project. You may refer to [my dataloader](https://github.com/yaoyao-liu/meta-transfer-learning/tree/master/pytorch/dataloader) if you don't need to use pickle. Otherwise, you may refer to [the official documents for pickle](https://docs.python.org/3/library/pickle.html).

**Comment by 123675** [comment]
thank you
